Updated website
SFTtech/openage-pr pull request #9
Opened 2020-02-12 23:09 UTC by simonsan

I've added links to linux, windows packages and the main repository on the left side.
Linked the forum and edited some links on the right side.

I've also updated the text on the right side to the one of the new website.

Updated main.css correspondingly to get three buttons to the middle of the left side of the page.

Screenshot of the new version:
![2020-02-13 00_07_47-openage - free strategy game engine](https://user-images.githubusercontent.com/14062932/74385888-e6eef380-4df4-11ea-8ff6-cd33981df623.png)

2020-02-13 10:59 UTC, TheJJ approved these changes
I think this would change the project direction very much, and claims things that are not (yet) true.
I would propose the following main content:
```
<p>You know Age of Empires. You know its bugs. You know the fun playing it.</p>
<p>We are creating a free (as in freedom) clone of the Age of Empires II engine in C++17 from scratch (GPLv3+). We use "modern" technologies like OpenGL/GLSL, Python, Qt5, CMake, ...</p>
<p>This allows people using GNU/Linux, BSD, macOS or Windows to play the game natively, minus features, plus additional epic bugs (or was it vice versa?).</p>
<p>We aim to create a game engine that provides the original look and feel</p>
<p>Until we have free replacement assets, we can import original media files provided by the user.</p>
<p>openage havs lots of improvement planed over the original components. Apart from better performance (multithreading, Vulkan, ...), we mainly focus making the engine dynamic: We designed our modding API with <a href="https://github.com/SFTtech/nyan/">nyan</a> and aim to expose many engine features over Python to mods.</p>
<p>openage is a huge and ambitious project, so we are glad about every helping hand. The only requirement is your enthusiasm :)</p>
<p>Just get in <a href="https://github.com/SFTtech/openage#contact">contact</a> with us if you have any questions on how to get started.</p>
</br>
```

2020-02-13 16:52 UTC, simonsan commented
New proposal:
![2020-02-13 17_50_55-Window](https://user-images.githubusercontent.com/14062932/74458077-747c2300-4e89-11ea-94df-0509a12becbb.png)

2020-02-27 00:43 UTC, heinezen requested changes

2020-02-27 00:43 UTC, heinezen commented on index.html
> +				<p>We always welcome new contributors! openage is a huge and ambitious project. There is more work than our small core dev team mainly run by volunteers can handle. The openage community is very
I would use commas here to make it more readable. There is more work than our small core dev team, mainly run by volunteers, can handle.

2020-02-27 00:43 UTC, heinezen commented on index.html
> +				<p><b>A look into the future:</b> openage has a lot of improvements planned. It is going to add completely new possibilities and will provide better performance due to different design decisions
We'll see about better performance :D I would not claim this as of yet, since so much can change until the release.

2020-02-29 21:30 UTC, TheJJ commented
I've updated the website and added new links and content ideas, adapted to the limited space requirements and goals of the project.

2020-02-29 21:30 UTC, closed without merging

2020-03-01 14:42 UTC, simonsan commented
That's honestly a bad move, that you merged something without even giving more feedback, heinezens feedback is still to be worked in and in general I'm still working on this. You changed things (the buttons that should be there for the launch of the forums) and made them invisible all-over not serving the purpose to invite people to our new platform - the forum.

2020-03-02 19:36 UTC, TheJJ commented
I'm sorry for closing this prematurely, I've just added some thoughts for improvements to the website directly. I think the website state is quite good now, but I'm of course open for further content improvements :)

The challenge for the website is to deliver the content in such a way it makes visitors curious about the project, and redirects them to the right places. We have to thwart ux antipattern such as information overload or highlighting things so obvious, they're overlooked (overexposure). I'm sure we can optimize the site even more, please continue sending pull requests for that :heavy_check_mark:

2020-03-02 21:07 UTC, simonsan commented
Can you please just open this PR again, a new PR of me would just have the same content again that we need to discuss. The buttons are there for a reason. **We want to push the forum as a new communication platform for its' release, that was the reason of this PR.** The text are still being worked on, as I've already stated, hence why heinezen made a review of the texts as well.